name: Dependabot Auto-merge
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-metadata:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      update-type: ${{ steps.metadata.outputs.update-type }}
      package-ecosystem: ${{ steps.metadata.outputs.package-ecosystem }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

  run-tests:
    needs: dependabot-metadata
    if: |
      needs.dependabot-metadata.outputs.package-ecosystem == 'npm'
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  auto-merge:
    needs: [dependabot-metadata, run-tests]
    if: |
      always() &&
      needs.dependabot-metadata.result == 'success' &&
      (needs.run-tests.result == 'success' || needs.run-tests.result == 'skipped') &&
      (needs.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' ||
       needs.dependabot-metadata.outputs.update-type == 'version-update:semver-minor')
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Enable auto-merge for Dependabot PRs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr review --approve "${{ github.event.pull_request.number }}"
          gh pr merge --auto --merge "${{ github.event.pull_request.number }}"
