name: Debug log

on: [push]

defaults:
  run:
    shell: bash

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  log:
    runs-on: ubuntu-latest

    steps:
      - run: echo "::debug::Set the Octocat variable"
