name: Debug log

on: [push]

defaults:
  run:
    shell: bash

jobs:
  log:
    runs-on: ubuntu-latest

    steps:
      - run: |
          set -x
          date
          hostname
      - run: echo "hello"
      - run: echo "::debug::Set the Octocat variable"
