name: Manual
on:
  push:
    inputs:
      greeting:
        type: string
        default: "Hello"
        required: true
        description: A cheerful word
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"
